# Site settings
author: R M
title: Journey into the Unknown - World of WebDev
header-img: img/home-bg.png
email: reachryanmui@gmail.com
copyright_name: R M
description: > # this means to ignore newlines until "baseurl:"
  WEB Development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Yumacorn

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
