# Site settings
author: Ryan Mui
title: Journey into the Unknown
header-img: img/home-bg.png
email: reachryanmui@gmail.com
copyright_name: Ryan Mui
description: > # this means to ignore newlines until "baseurl:"
  World of Web Dev Awaits 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Yumacorn

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
